
set COMPILATION_TYPE=RelWithDebInfo

mkdir build

cmake -DRAY_IT_USE_FLOATS=OFF -DRAY_IT_COMPILATION_TYPE=%COMPILATION_TYPE% . -G "Visual Studio 17 2022" -A x64 -DCMAKE_CXX_FLAGS="/MP3 /EHsc /Ot" -B"build\%COMPILATION_TYPE%"

cmake --build "build\%COMPILATION_TYPE%" --config %COMPILATION_TYPE%

copy build\%COMPILATION_TYPE%\%COMPILATION_TYPE%\Ray-it.exe .\Ray-it_%COMPILATION_TYPE%.exe